index:
    resource: "@IndexBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"