parameters:
    airtrade.service_base_url:   "http://otvapitest.airtrade.com"
    airtrade.account_code:       "MontysAccount"
    airtrade.session_params:
        name:               "Otravo"
        application_type:   "WebApi"
        culture_code:       "nl-NL"
        affiliate_code:     "Vliegticketsnl"
        channel_code:       "ch" 
        
        password:           "31iq66vs87Q=3B_ST"
        secret:             "secret"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    http_client:
        class:      GuzzleHttp\Client
        
    airtrade_user_session:
        class:      Services\Airtrade\RestUserSession
        arguments:    ["@session", "%airtrade.account_code%", "%airtrade.session_params%"]
        public: false

    airtrade_client:
        class:      Services\Airtrade\RestClient
        arguments:    ["@http_client", "@airtrade_user_session", "%airtrade.service_base_url%", "%airtrade.account_code%"]