parameters:
    service_base_url:   "http://otvapitest.airtrade.com"
    account_code:       "MontysAccount"
    session_params:
        name:               "Otravo"
        application_type:   "WebApi"
        culture_code:       "nl-NL"
        affiliate_code:     "Vliegticketsnl"
        channel_code:       "ch" 
        
        password:           "31iq66vs87Q=3B_ST"
        secret:             "secret"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    http_client:
        class:      Guzzle\Http\Client
        
    airtrade_client_session:
        class:      Services\Airtrade\RestClientSession
        arguments:    ["%account_code%", "%session_params%"]

    airtrade_client:
        class:      Services\Airtrade\RestClient
        arguments:    ["@http_client", "@airtrade_client_session", "%service_base_url%", "%account_code%"]